### ISSUE TITLE
Can't make gym environment

### ISSUE THREAD

**Issue by mgarciaortiz** [MiniHackPlanet/MiniHack#1]
Hi,

I am trying out MiniHack. 
When I follow these steps: 
```
>>> import gym
>>> import minihack
>>> env = gym.make("MiniHack-River-v0")
```

I get the following error:
```
__init__() got an unexpected keyword argument 'spawn_monsters' 
```

I just installed nle and Minihack in a virtual environment, if that helps, using the installation steps on Minihack readme (but I think the github repo link on the readme is an old one).

Cheers

Michael

**Comment by MiniHackPlanet** [comment]
Hi Michael.

I've updated the Readme. Thanks for pointing out about the repository link.

Could you please confirm that you installed NLE from the current master branch, rather than latest release?
```pip install git+https://github.com/facebookresearch/nle.git```
The` spawn_monsters` has only been [recently](https://github.com/facebookresearch/nle/commit/a9fc3138c1ec25ab3527223a960c41923ca5c527) added to nle.

**Comment by mgarciaortiz** [comment]
Ok that was the issue. I didn't install the latest version.
It works now.

Sorry about that!

**Comment by MiniHackPlanet** [comment]
Great! Happy to help!
